using System.Text.Json;
using PlatformAuditEventService.DTOs.Ingest;
using PlatformAuditEventService.Entities;

namespace PlatformAuditEventService.Mappers;

/// <summary>
/// Maps an <see cref="IngestAuditEventRequest"/> to a fully-initialised
/// <see cref="AuditEventRecord"/> ready for persistence.
///
/// Division of responsibilities (mapper vs. ingest service):
///   Mapper   — pure structural translation; no I/O, no side-effects,
///              no ID generation, no hash computation.
///   Service  — AuditId generation, RecordedAtUtc capture, idempotency
///              check, hash computation, chain lookup, append.
///
/// All identity and hash values that are <c>init</c>-only on the entity
/// must be generated by the caller and passed into <see cref="ToEntity"/>.
/// This keeps the mapper a deterministic, side-effect-free function.
///
/// UUIDv7 note:
///   The service currently passes <c>Guid.NewGuid()</c>. When a UUIDv7
///   factory is available (time-ordered GUIDs, better clustered-index
///   locality on MySQL), only the service changes — the mapper is unaffected.
/// </summary>
public static class AuditEventRecordMapper
{
    private static readonly JsonSerializerOptions _jsonOpts = new()
    {
        WriteIndented        = false,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>
    /// Translates the inbound DTO into a fully-initialised <see cref="AuditEventRecord"/>.
    /// </summary>
    /// <param name="req">The validated ingest request.</param>
    /// <param name="auditId">
    /// Platform-assigned public identifier for this record. Generated by the ingest
    /// service so the hash can be computed over the same value before entity creation.
    /// </param>
    /// <param name="now">
    /// Server receipt timestamp (UTC). Used as <c>RecordedAtUtc</c> and as
    /// <c>OccurredAtUtc</c> fallback when the caller omits the event time.
    /// </param>
    /// <param name="correlationIdOverride">
    /// Optional correlation ID that overrides <c>req.CorrelationId</c>.
    /// Used by the batch pipeline to propagate <c>BatchCorrelationId</c> as a
    /// fallback for items that did not supply their own correlation ID.
    /// </param>
    /// <param name="hash">
    /// HMAC-SHA256 integrity hash computed by the ingest service over the canonical
    /// fields of this record. Pass null when integrity signing is disabled.
    /// </param>
    /// <param name="previousHash">
    /// Hash of the immediately preceding record in the same (TenantId, SourceSystem)
    /// chain. Null for the first record in a chain or when signing is disabled.
    /// </param>
    public static AuditEventRecord ToEntity(
        IngestAuditEventRequest req,
        Guid            auditId,
        DateTimeOffset  now,
        string?         correlationIdOverride = null,
        string?         hash                 = null,
        string?         previousHash         = null)
    {
        return new AuditEventRecord
        {
            // ── Identity ──────────────────────────────────────────────────
            AuditId = auditId,
            EventId = req.EventId,

            // ── Classification ────────────────────────────────────────────
            EventType     = req.EventType,
            EventCategory = req.EventCategory,

            // ── Source provenance ─────────────────────────────────────────
            SourceSystem      = req.SourceSystem,
            SourceService     = req.SourceService,
            SourceEnvironment = req.SourceEnvironment,

            // ── Scope / tenancy ───────────────────────────────────────────
            PlatformId     = ParseGuid(req.Scope.PlatformId),
            TenantId       = req.Scope.TenantId,
            OrganizationId = req.Scope.OrganizationId,
            UserScopeId    = req.Scope.UserId,
            ScopeType      = req.Scope.ScopeType,

            // ── Actor ─────────────────────────────────────────────────────
            ActorId        = req.Actor.Id,
            ActorType      = req.Actor.Type,
            ActorName      = req.Actor.Name,
            ActorIpAddress = req.Actor.IpAddress,
            ActorUserAgent = req.Actor.UserAgent,

            // ── Target entity ─────────────────────────────────────────────
            EntityType = req.Entity?.Type,
            EntityId   = req.Entity?.Id,

            // ── Action description ────────────────────────────────────────
            Action      = req.Action,
            Description = req.Description,

            // ── State snapshots (stored verbatim as raw JSON strings) ─────
            BeforeJson   = req.Before,
            AfterJson    = req.After,
            MetadataJson = req.Metadata,

            // ── Correlation / tracing ─────────────────────────────────────
            // Override wins when the batch pipeline supplies a fallback.
            CorrelationId = correlationIdOverride ?? req.CorrelationId,
            RequestId     = req.RequestId,
            SessionId     = req.SessionId,

            // ── Access control ────────────────────────────────────────────
            VisibilityScope = req.Visibility,
            Severity        = req.Severity,

            // ── Timestamps ────────────────────────────────────────────────
            OccurredAtUtc = req.OccurredAtUtc ?? now,   // fall back to server receipt time
            RecordedAtUtc = now,

            // ── Integrity chain ────────────────────────────────────────────
            // Both are null when IntegrityOptions.HmacKeyBase64 is not configured.
            Hash         = hash,
            PreviousHash = previousHash,

            // ── Dedup / replay ────────────────────────────────────────────
            IdempotencyKey = req.IdempotencyKey,
            IsReplay       = req.IsReplay,

            // ── Tags ──────────────────────────────────────────────────────
            TagsJson = SerializeTags(req.Tags),
        };
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// Attempts to parse a string as a <see cref="Guid"/>.
    /// Returns null when the input is null, empty, or not a valid GUID format.
    /// </summary>
    private static Guid? ParseGuid(string? value) =>
        Guid.TryParse(value, out var g) ? g : null;

    /// <summary>
    /// Serializes a tag list to a compact JSON array string, or null when the list
    /// is null or empty. Stored as a raw <c>text</c> column; parsed by query consumers.
    /// </summary>
    private static string? SerializeTags(IReadOnlyList<string>? tags) =>
        tags is { Count: > 0 }
            ? JsonSerializer.Serialize(tags, _jsonOpts)
            : null;
}
