/**
 * /notifications/sms-incidents/alerts — LS-NOTIF-SMS-012
 *
 * SMS operational alert list with resolve / suppress / evaluate actions.
 *
 * Server Component: fetches alert list + summary, passes to AlertsPanel (Client Component).
 *
 * URL params:
 *   ?status=active|resolved|suppressed  — alert status filter
 *   ?severity=warning|critical          — severity filter
 *   ?alertType=<code>                   — alert type code filter
 *   ?offset=<n>                         — pagination offset (page size 25)
 *
 * Security:
 *   - requirePlatformAdmin() gates the entire page.
 *   - No credentials, raw targets, or phone numbers rendered.
 */

import { requirePlatformAdmin } from '@/lib/auth-guards';
import { CCShell }              from '@/components/shell/cc-shell';
import { smsIncidentsApi }      from '@/lib/sms-incidents-api';
import { AlertsPanel }          from '@/components/sms-incidents/alerts-panel';

export const dynamic = 'force-dynamic';

const PAGE_SIZE = 25;

function SectionErr({ label, message }: { label: string; message: string }) {
  return (
    <div className="flex items-center gap-2 px-4 py-3 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700">
      <i className="ri-error-warning-line" aria-hidden /> {label}: {message}
    </div>
  );
}

export default async function AlertsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const session = await requirePlatformAdmin();

  const sp       = await searchParams;
  const status   = typeof sp.status    === 'string' ? sp.status    : undefined;
  const severity = typeof sp.severity  === 'string' ? sp.severity  : undefined;
  const alertType = typeof sp.alertType === 'string' ? sp.alertType : undefined;
  const offset   = typeof sp.offset    === 'string' ? Math.max(0, parseInt(sp.offset, 10) || 0) : 0;

  const [listResult, summaryResult] = await Promise.allSettled([
    smsIncidentsApi.listAlerts({ status, severity, alertType, limit: PAGE_SIZE, offset }),
    smsIncidentsApi.getAlertSummary(),
  ]);

  const list    = listResult.status    === 'fulfilled' ? listResult.value    : null;
  const summary = summaryResult.status === 'fulfilled' ? summaryResult.value : null;
  const listErr    = listResult.status    === 'rejected'
    ? String((listResult.reason as Error)?.message ?? 'Unknown error') : null;
  const summaryErr = summaryResult.status === 'rejected'
    ? String((summaryResult.reason as Error)?.message ?? 'Unknown error') : null;

  return (
    <CCShell userEmail={session.email}>
      <div className="px-6 py-6 max-w-6xl mx-auto space-y-6">

        <div>
          <h1 className="text-xl font-semibold text-gray-900">SMS Alert List</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Operational alerts generated by the SMS monitoring evaluation engine.
          </p>
        </div>

        {summaryErr && <SectionErr label="Alert summary unavailable" message={summaryErr} />}
        {listErr    && <SectionErr label="Alert list unavailable"    message={listErr}    />}

        <AlertsPanel
          initialList={list}
          initialSummary={summary}
          initialStatus={status}
          initialSeverity={severity}
          initialAlertType={alertType}
          initialOffset={offset}
          pageSize={PAGE_SIZE}
        />

      </div>
    </CCShell>
  );
}
