apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev     #Make sure this matches the namespace you want to deploy to
  name: jenkins-deployer  #Name of the role that Jenkins will use to deploy to the dev namespace, this already exit -GYJ
rules:
- apiGroups: ["", "apps"]
  resources:
    - pods
    - services
    - deployments
    - namespaces
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete