apiVersion: v1
kind: Service

metadata:
 name: dotnet-core-service
 namespace: dev
 annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

 #labels:
 #app: dotnet-core-service

spec:
  type: LoadBalancer
  selector:
   app: dotnet-core-service

  ports:
  - port: 80
    targetPort: 8080