// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenant.Infrastructure.Data;

#nullable disable

namespace Tenant.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260423220000_AddProvisioningState")]
    partial class AddProvisioningState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tenant.Domain.MigrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowCreates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowUpdates")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Conflicts")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Errors")
                        .HasColumnType("int");

                    b.Property<bool>("IdentityAccessible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("TenantAccessible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TenantsCreated")
                        .HasColumnType("int");

                    b.Property<int>("TenantsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("TenantsUpdated")
                        .HasColumnType("int");

                    b.Property<int>("TotalScanned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("tenant_MigrationRuns", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.MigrationRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("BrandingUpserted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DomainUpserted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Errors")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("IdentityTenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("TenantUpserted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Warnings")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityTenantId");

                    b.HasIndex("RunId");

                    b.ToTable("tenant_MigrationRunItems", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LastProvisioningError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Locale")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("LogoDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LogoWhiteDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ProvisionedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProvisioningStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasDefaultValue("Unknown")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Subdomain")
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasFilter("`Subdomain` IS NOT NULL");

                    b.ToTable("tenant_Tenants", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.TenantBranding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("BrandName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FaviconDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LogoDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LogoWhiteDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("SupportEmailOverride")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("SupportPhoneOverride")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TextColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrlOverride")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("tenant_Brandings", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.TenantCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ProductEntitlementId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntitlementId")
                        .HasDatabaseName("IX_tenant_Capabilities_ProductEntitlementId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_tenant_Capabilities_TenantId");

                    b.HasIndex("TenantId", "CapabilityKey")
                        .HasDatabaseName("IX_tenant_Capabilities_TenantId_CapabilityKey");

                    b.ToTable("tenant_Capabilities", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DomainType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("varchar(253)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .HasDatabaseName("IX_tenant_Domains_Host");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_tenant_Domains_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_tenant_Domains_TenantId");

                    b.ToTable("tenant_Domains", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.TenantProductEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlanCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProductDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_tenant_ProductEntitlements_TenantId");

                    b.HasIndex("TenantId", "IsDefault")
                        .HasDatabaseName("IX_tenant_ProductEntitlements_TenantId_IsDefault");

                    b.HasIndex("TenantId", "ProductKey")
                        .HasDatabaseName("IX_tenant_ProductEntitlements_TenantId_ProductKey");

                    b.ToTable("tenant_ProductEntitlements", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_tenant_Settings_TenantId");

                    b.HasIndex("TenantId", "ProductKey")
                        .HasDatabaseName("IX_tenant_Settings_TenantId_ProductKey");

                    b.HasIndex("TenantId", "SettingKey")
                        .HasDatabaseName("IX_tenant_Settings_TenantId_SettingKey");

                    b.ToTable("tenant_Settings", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.MigrationRunItem", b =>
                {
                    b.HasOne("Tenant.Domain.MigrationRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Tenant.Domain.TenantBranding", b =>
                {
                    b.HasOne("Tenant.Domain.Tenant", "Tenant")
                        .WithOne("Branding")
                        .HasForeignKey("Tenant.Domain.TenantBranding", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.TenantCapability", b =>
                {
                    b.HasOne("Tenant.Domain.TenantProductEntitlement", "ProductEntitlement")
                        .WithMany()
                        .HasForeignKey("ProductEntitlementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tenant.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductEntitlement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.TenantDomain", b =>
                {
                    b.HasOne("Tenant.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.TenantProductEntitlement", b =>
                {
                    b.HasOne("Tenant.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.TenantSetting", b =>
                {
                    b.HasOne("Tenant.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.MigrationRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tenant.Domain.Tenant", b =>
                {
                    b.Navigation("Branding");
                });
#pragma warning restore 612, 618
        }
    }
}
