// <auto-generated />
using System;
using Liens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Liens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LiensDbContext))]
    [Migration("20260414041807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Liens.Domain.Entities.BillOfSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BillOfSaleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuyerContactName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EffectiveAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LienOfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal>("OriginalLienAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerContactName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Terms")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_BillsOfSale_DocumentId");

                    b.HasIndex("LienId")
                        .HasDatabaseName("IX_BillsOfSale_LienId");

                    b.HasIndex("LienOfferId")
                        .HasDatabaseName("IX_BillsOfSale_LienOfferId");

                    b.HasIndex("TenantId", "BillOfSaleNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_BillsOfSale_TenantId_BillOfSaleNumber");

                    b.HasIndex("TenantId", "BuyerOrgId")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_BuyerOrgId");

                    b.HasIndex("TenantId", "SellerOrgId")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_SellerOrgId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_Status");

                    b.ToTable("liens_BillsOfSale", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClaimNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly?>("ClientDob")
                        .HasColumnType("date");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DateOfIncident")
                        .HasColumnType("date");

                    b.Property<decimal?>("DemandAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("InsuranceCarrier")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("SettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Cases_TenantId_CaseNumber");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Cases_TenantId_Status");

                    b.HasIndex("TenantId", "OrgId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Cases_TenantId_OrgId_CreatedAtUtc");

                    b.HasIndex("TenantId", "OrgId", "Status")
                        .HasDatabaseName("IX_Cases_TenantId_OrgId_Status");

                    b.ToTable("liens_Cases", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_Contacts_TenantId_Email");

                    b.HasIndex("TenantId", "OrgId", "ContactType")
                        .HasDatabaseName("IX_Contacts_TenantId_OrgId_ContactType");

                    b.HasIndex("TenantId", "OrgId", "DisplayName")
                        .HasDatabaseName("IX_Contacts_TenantId_OrgId_DisplayName");

                    b.ToTable("liens_Contacts", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Facilities_OrganizationId");

                    b.HasIndex("TenantId", "Code")
                        .HasDatabaseName("IX_Facilities_TenantId_Code");

                    b.HasIndex("TenantId", "OrgId", "Name")
                        .HasDatabaseName("IX_Facilities_TenantId_OrgId_Name");

                    b.ToTable("liens_Facilities", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Lien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BuyingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("HoldingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LienNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LienType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal?>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayoffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SellingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectLastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("SubjectPartyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("IX_Liens_CaseId");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("IX_Liens_FacilityId");

                    b.HasIndex("TenantId", "BuyingOrgId")
                        .HasDatabaseName("IX_Liens_TenantId_BuyingOrgId");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Liens_TenantId_CreatedAtUtc");

                    b.HasIndex("TenantId", "LienNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Liens_TenantId_LienNumber");

                    b.HasIndex("TenantId", "LienType")
                        .HasDatabaseName("IX_Liens_TenantId_LienType");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_Status");

                    b.HasIndex("TenantId", "HoldingOrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_HoldingOrgId_Status");

                    b.HasIndex("TenantId", "OrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_OrgId_Status");

                    b.HasIndex("TenantId", "SellingOrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_SellingOrgId_Status");

                    b.ToTable("liens_Liens", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal>("OfferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OfferedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LienId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_Status");

                    b.HasIndex("TenantId", "BuyerOrgId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_BuyerOrgId_Status");

                    b.HasIndex("TenantId", "LienId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_LienId_Status");

                    b.HasIndex("TenantId", "SellerOrgId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_SellerOrgId_Status");

                    b.ToTable("liens_LienOffers", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LookupValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("IX_LookupValues_TenantId_Category");

                    b.HasIndex("TenantId", "Category", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LookupValues_TenantId_Category_Code");

                    b.ToTable("liens_LookupValues", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.BillOfSale", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liens.Domain.Entities.LienOffer", null)
                        .WithMany()
                        .HasForeignKey("LienOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.Lien", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Liens.Domain.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienOffer", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
