// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitoring.Infrastructure.Persistence;

#nullable disable

namespace Monitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260420035016_AddEntityCurrentStatus")]
    partial class AddEntityCurrentStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Monitoring.Domain.Monitoring.CheckResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checked_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("entity_name");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("error_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("MonitoredEntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("monitored_entity_id");

                    b.Property<string>("MonitoringType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("monitoring_type");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("outcome");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("succeeded");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAtUtc")
                        .HasDatabaseName("ix_check_results_checked_at_utc");

                    b.HasIndex("MonitoredEntityId")
                        .HasDatabaseName("ix_check_results_monitored_entity_id");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_check_results_outcome");

                    b.ToTable("check_results", (string)null);
                });

            modelBuilder.Entity("Monitoring.Domain.Monitoring.EntityCurrentStatus", b =>
                {
                    b.Property<Guid>("MonitoredEntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("monitored_entity_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("current_status");

                    b.Property<DateTime>("LastCheckedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_checked_at_utc");

                    b.Property<long>("LastElapsedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_elapsed_ms");

                    b.Property<string>("LastErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_error_type");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("last_message");

                    b.Property<string>("LastOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("last_outcome");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("last_status_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("MonitoredEntityId");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("ix_entity_current_status_current_status");

                    b.ToTable("entity_current_status", (string)null);
                });

            modelBuilder.Entity("Monitoring.Domain.Monitoring.MonitoredEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("impact_level");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MonitoringType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("monitoring_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("scope");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("target");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_monitored_entities_name");

                    b.HasIndex("EntityType", "MonitoringType")
                        .HasDatabaseName("ix_monitored_entities_entity_type_monitoring_type");

                    b.ToTable("monitored_entities", (string)null);
                });

            modelBuilder.Entity("Monitoring.Domain.Monitoring.CheckResultRecord", b =>
                {
                    b.HasOne("Monitoring.Domain.Monitoring.MonitoredEntity", null)
                        .WithMany()
                        .HasForeignKey("MonitoredEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monitoring.Domain.Monitoring.EntityCurrentStatus", b =>
                {
                    b.HasOne("Monitoring.Domain.Monitoring.MonitoredEntity", null)
                        .WithMany()
                        .HasForeignKey("MonitoredEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
