namespace PlatformAuditEventService.DTOs.Analytics;

/// <summary>An actor ranked by event count.</summary>
public sealed class AuditTopActorItem
{
    /// <summary>Stable actor identifier.</summary>
    public required string ActorId { get; init; }

    /// <summary>Display name snapshot (most recent name seen for this actor in the window).</summary>
    public string? ActorName { get; init; }

    /// <summary>Total events generated by this actor within the query scope.</summary>
    public required long Count { get; init; }
}
