// <auto-generated />
using System;
using Documents.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Documents.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DocsDbContext))]
    [Migration("20260418043704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Documents.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_version_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_type_id");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LegalHoldAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("legal_hold_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_type");

                    b.Property<DateTime?>("RetainUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retain_until");

                    b.Property<DateTime?>("ScanCompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scan_completed_at");

                    b.Property<int?>("ScanDurationMs")
                        .HasColumnType("int")
                        .HasColumnName("scan_duration_ms");

                    b.Property<string>("ScanEngineVersion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("scan_engine_version");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scan_status");

                    b.Property<string>("ScanThreats")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("scan_threats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<int>("VersionCount")
                        .HasColumnType("int")
                        .HasColumnName("version_count");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_documents_tenant");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("idx_documents_product");

                    b.HasIndex("TenantId", "ReferenceId")
                        .HasDatabaseName("idx_documents_reference");

                    b.ToTable("docs_documents", (string)null);
                });

            modelBuilder.Entity("Documents.Domain.Entities.DocumentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("actor_email");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .HasColumnType("json")
                        .HasColumnName("detail");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_audits_tenant");

                    b.HasIndex("DocumentId", "TenantId")
                        .HasDatabaseName("idx_audits_document");

                    b.ToTable("docs_document_audits", (string)null);
                });

            modelBuilder.Entity("Documents.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext")
                        .HasColumnName("checksum");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_id");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("label");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mime_type");

                    b.Property<DateTime?>("ScanCompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scan_completed_at");

                    b.Property<int?>("ScanDurationMs")
                        .HasColumnType("int")
                        .HasColumnName("scan_duration_ms");

                    b.Property<string>("ScanEngineVersion")
                        .HasColumnType("longtext")
                        .HasColumnName("scan_engine_version");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scan_status");

                    b.Property<string>("ScanThreats")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("scan_threats");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "TenantId")
                        .HasDatabaseName("idx_versions_document");

                    b.ToTable("docs_document_versions", (string)null);
                });

            modelBuilder.Entity("Documents.Domain.Entities.FileBlob", b =>
                {
                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("storage_key");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("StorageKey");

                    b.ToTable("docs_file_blobs", (string)null);
                });

            modelBuilder.Entity("Documents.Domain.Entities.DocumentAudit", b =>
                {
                    b.HasOne("Documents.Domain.Entities.Document", "Document")
                        .WithMany("Audits")
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Documents.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Documents.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Documents.Domain.Entities.Document", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
