// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Task.Infrastructure.Persistence;

#nullable disable

namespace Task.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20260421000010_AddStageTransitions")]
    partial class AddStageTransitions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
