// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Infrastructure.Persistence;

#nullable disable

namespace Task.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    partial class TasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Task.Domain.Entities.PlatformTask", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid?>("AssignedUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("ClosedByUserId").HasColumnType("char(36)");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime(6)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("CurrentStageId").HasColumnType("char(36)");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("varchar(4000)");
                    b.Property<DateTime?>("DueAt").HasColumnType("datetime(6)");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasDefaultValue("MEDIUM").HasColumnType("varchar(20)");
                    b.Property<string>("Scope").IsRequired().HasMaxLength(20).HasDefaultValue("GENERAL").HasColumnType("varchar(20)");
                    b.Property<Guid?>("GeneratingTemplateId").HasColumnType("char(36)");
                    b.Property<Guid?>("GenerationRuleId").HasColumnType("char(36)");
                    b.Property<Guid?>("SourceEntityId").HasColumnType("char(36)");
                    b.Property<string>("SourceEntityType").HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("SourceProductCode").HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(30).HasDefaultValue("OPEN").HasColumnType("varchar(30)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("WorkflowInstanceId").HasColumnType("char(36)");
                    b.Property<DateTime?>("WorkflowLinkageChangedAt").HasColumnType("datetime(6)");
                    b.Property<string>("WorkflowStepKey").HasMaxLength(100).HasColumnType("varchar(100)");
                    // TASK-FLOW-02 — queue assignment metadata
                    b.Property<string>("AssignmentMode").HasMaxLength(20).HasColumnType("varchar(20)");
                    b.Property<string>("AssignedRole").HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("AssignedOrgId").HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<DateTime?>("AssignedAt").HasColumnType("datetime(6)");
                    b.Property<string>("AssignedBy").HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("AssignmentReason").HasMaxLength(500).HasColumnType("varchar(500)");
                    // TASK-FLOW-02 — lifecycle timestamps
                    b.Property<DateTime?>("StartedAt").HasColumnType("datetime(6)");
                    b.Property<DateTime?>("CancelledAt").HasColumnType("datetime(6)");
                    // TASK-FLOW-02 — SLA state
                    b.Property<string>("SlaStatus").IsRequired().HasMaxLength(20).HasDefaultValue("OnTrack").HasColumnType("varchar(20)");
                    b.Property<DateTime?>("SlaBreachedAt").HasColumnType("datetime(6)");
                    b.Property<DateTime?>("LastSlaEvaluatedAt").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "Status" }, "IX_Tasks_TenantId_Status");
                    b.HasIndex(new[] { "TenantId", "AssignedUserId" }, "IX_Tasks_TenantId_AssignedUserId");
                    b.HasIndex(new[] { "TenantId", "Scope", "SourceProductCode" }, "IX_Tasks_TenantId_Scope_Product");
                    b.HasIndex(new[] { "TenantId", "CreatedAtUtc" }, "IX_Tasks_TenantId_CreatedAt");
                    b.HasIndex(new[] { "TenantId", "CurrentStageId" }, "IX_Tasks_TenantId_StageId");
                    b.HasIndex(new[] { "WorkflowInstanceId" }, "IX_Tasks_WorkflowInstanceId");
                    b.HasIndex(new[] { "TenantId", "SourceEntityType", "SourceEntityId" }, "IX_Tasks_SourceEntity");
                    b.HasIndex(new[] { "TenantId", "AssignedUserId", "Status" }, "IX_Tasks_TenantId_AssignedUser_Status");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "GenerationRuleId" }, "IX_Tasks_TenantId_Product_GenerationRule");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "GeneratingTemplateId" }, "IX_Tasks_TenantId_Product_GeneratingTemplate");
                    // TASK-FLOW-02 — queue read indexes
                    b.HasIndex(new[] { "TenantId", "AssignmentMode", "AssignedRole" }, "IX_Tasks_TenantId_AssignmentMode_Role");
                    b.HasIndex(new[] { "TenantId", "AssignmentMode", "AssignedOrgId" }, "IX_Tasks_TenantId_AssignmentMode_Org");
                    b.ToTable("tasks_Tasks");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskLinkedEntity", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("EntityId").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("RelationshipType").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("SourceProductCode").HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<Guid>("TaskId").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TaskId" }, "IX_LinkedEntities_TaskId");
                    b.HasIndex(new[] { "TenantId", "EntityType", "EntityId" }, "IX_LinkedEntities_EntityRef");
                    // TASK-B05 (TASK-017) — unique constraint added in migration 20260421000006
                    b.HasIndex(new[] { "TaskId", "EntityType", "EntityId" }, "UX_LinkedEntities_TaskId_EntityType_EntityId").IsUnique();
                    b.ToTable("tasks_LinkedEntities");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskNote", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<string>("Note").IsRequired().HasMaxLength(4000).HasColumnType("varchar(4000)");
                    b.Property<Guid>("TaskId").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "TaskId" }, "IX_Notes_TenantId_TaskId");
                    b.ToTable("tasks_Notes");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<string>("Action").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Details").HasMaxLength(500).HasColumnType("varchar(500)");
                    b.Property<Guid>("PerformedByUserId").HasColumnType("char(36)");
                    b.Property<Guid>("TaskId").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "TaskId" }, "IX_History_TenantId_TaskId");
                    b.ToTable("tasks_History");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskStageConfig", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("SourceProductCode").HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<int>("DisplayOrder").HasColumnType("int");
                    b.Property<bool>("IsActive").IsRequired().HasDefaultValue(true).HasColumnType("tinyint(1)");
                    b.Property<string>("ProductSettingsJson").HasColumnType("TEXT");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode" }, "IX_StageConfigs_TenantId_Product");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "Code" }, "IX_StageConfigs_TenantId_Product_Code").IsUnique();
                    b.ToTable("tasks_StageConfigs");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskGovernanceSettings", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("SourceProductCode").HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<bool>("RequireAssignee").IsRequired().HasDefaultValue(false).HasColumnType("tinyint(1)");
                    b.Property<bool>("RequireDueDate").IsRequired().HasDefaultValue(false).HasColumnType("tinyint(1)");
                    b.Property<bool>("RequireStage").IsRequired().HasDefaultValue(false).HasColumnType("tinyint(1)");
                    b.Property<bool>("AllowUnassign").IsRequired().HasDefaultValue(true).HasColumnType("tinyint(1)");
                    b.Property<bool>("AllowCancel").IsRequired().HasDefaultValue(true).HasColumnType("tinyint(1)");
                    b.Property<bool>("AllowCompleteWithoutStage").IsRequired().HasDefaultValue(true).HasColumnType("tinyint(1)");
                    b.Property<bool>("AllowNotesOnClosedTasks").IsRequired().HasDefaultValue(false).HasColumnType("tinyint(1)");
                    b.Property<string>("DefaultPriority").IsRequired().HasMaxLength(20).HasDefaultValue("MEDIUM").HasColumnType("varchar(20)");
                    b.Property<string>("DefaultTaskScope").IsRequired().HasMaxLength(20).HasDefaultValue("GENERAL").HasColumnType("varchar(20)");
                    b.Property<int>("Version").IsRequired().HasDefaultValue(1).HasColumnType("int");
                    b.Property<string>("ProductSettingsJson").HasColumnType("TEXT");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode" }, "IX_GovernanceSettings_TenantId_Product").IsUnique();
                    b.ToTable("tasks_GovernanceSettings");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("SourceProductCode").HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<string>("Description").HasMaxLength(1000).HasColumnType("varchar(1000)");
                    b.Property<string>("DefaultTitle").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                    b.Property<string>("DefaultDescription").HasMaxLength(4000).HasColumnType("varchar(4000)");
                    b.Property<string>("DefaultPriority").IsRequired().HasMaxLength(20).HasDefaultValue("MEDIUM").HasColumnType("varchar(20)");
                    b.Property<string>("DefaultScope").IsRequired().HasMaxLength(20).HasDefaultValue("GENERAL").HasColumnType("varchar(20)");
                    b.Property<int?>("DefaultDueInDays").HasColumnType("int");
                    b.Property<Guid?>("DefaultStageId").HasColumnType("char(36)");
                    b.Property<string>("ProductSettingsJson").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").IsRequired().HasDefaultValue(true).HasColumnType("tinyint(1)");
                    b.Property<int>("Version").IsRequired().HasDefaultValue(1).HasColumnType("int");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode" }, "IX_Templates_TenantId_Product");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "Code" }, "IX_Templates_TenantId_Product_Code").IsUnique();
                    b.ToTable("tasks_Templates");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskReminder", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid>("TaskId").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("ReminderType").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                    b.Property<DateTime>("RemindAt").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("PENDING").HasColumnType("varchar(20)");
                    b.Property<DateTime?>("LastAttemptAt").HasColumnType("datetime(6)");
                    b.Property<DateTime?>("SentAt").HasColumnType("datetime(6)");
                    b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("varchar(500)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "TaskId" }, "IX_Reminders_TenantId_TaskId");
                    b.HasIndex(new[] { "Status", "RemindAt" }, "IX_Reminders_Status_RemindAt");
                    b.ToTable("tasks_Reminders");
                });

            modelBuilder.Entity("Task.Domain.Entities.TaskStageTransition", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("char(36)");
                    b.Property<Guid>("TenantId").HasColumnType("char(36)");
                    b.Property<string>("SourceProductCode").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                    b.Property<Guid>("FromStageId").HasColumnType("char(36)");
                    b.Property<Guid>("ToStageId").HasColumnType("char(36)");
                    b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasDefaultValue(true);
                    b.Property<int>("SortOrder").HasColumnType("int").HasDefaultValue(0);
                    b.Property<Guid>("CreatedByUserId").HasColumnType("char(36)");
                    b.Property<Guid?>("UpdatedByUserId").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode" }, "IX_StageTransitions_TenantId_Product");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "FromStageId" }, "IX_StageTransitions_FromStage");
                    b.HasIndex(new[] { "TenantId", "SourceProductCode", "FromStageId", "ToStageId" }, "UX_StageTransitions_Unique").IsUnique();
                    b.ToTable("tasks_StageTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
