// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Comms.Infrastructure.Persistence;

#nullable disable

namespace Comms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommsDbContext))]
    partial class CommsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Comms.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VisibilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LastActivityAtUtc")
                        .HasDatabaseName("IX_Conversations_TenantId_LastActivity");

                    b.HasIndex("TenantId", "ContextType", "ContextId")
                        .HasDatabaseName("IX_Conversations_TenantId_Context");

                    b.HasIndex("TenantId", "OrgId", "Status")
                        .HasDatabaseName("IX_Conversations_TenantId_OrgId_Status");

                    b.ToTable("comms_Conversations", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastAssignedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UnassignedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedUserId")
                        .HasDatabaseName("IX_Assignments_TenantId_AssignedUserId");

                    b.HasIndex("TenantId", "AssignmentStatus")
                        .HasDatabaseName("IX_Assignments_TenantId_AssignmentStatus");

                    b.HasIndex("TenantId", "ConversationId")
                        .IsUnique()
                        .HasDatabaseName("IX_Assignments_TenantId_ConversationId");

                    b.HasIndex("TenantId", "QueueId")
                        .HasDatabaseName("IX_Assignments_TenantId_QueueId");

                    b.ToTable("comms_ConversationAssignments", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanReply")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ExternalName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "UserId", "IsActive")
                        .HasDatabaseName("IX_Participants_ConversationId_UserId_IsActive");

                    b.HasIndex("TenantId", "ConversationId", "IsActive")
                        .HasDatabaseName("IX_Participants_TenantId_ConversationId_Active");

                    b.HasIndex("TenantId", "UserId", "IsActive")
                        .HasDatabaseName("IX_Participants_TenantId_UserId_Active");

                    b.ToTable("comms_ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Queues_TenantId_Code");

                    b.HasIndex("TenantId", "IsDefault")
                        .HasDatabaseName("IX_Queues_TenantId_IsDefault");

                    b.ToTable("comms_ConversationQueues", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationReadState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastReadAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("TenantId", "ConversationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReadStates_TenantId_ConversationId_UserId");

                    b.ToTable("comms_ConversationReadStates", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationSlaState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("BreachedFirstResponse")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BreachedResolution")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("FirstResponseAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FirstResponseDueAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ResolutionDueAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SlaStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("WaitingOn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BreachedFirstResponse")
                        .HasDatabaseName("IX_SlaState_TenantId_BreachedFirstResponse");

                    b.HasIndex("TenantId", "BreachedResolution")
                        .HasDatabaseName("IX_SlaState_TenantId_BreachedResolution");

                    b.HasIndex("TenantId", "ConversationId")
                        .IsUnique()
                        .HasDatabaseName("IX_SlaState_TenantId_ConversationId");

                    b.HasIndex("TenantId", "Priority")
                        .HasDatabaseName("IX_SlaState_TenantId_Priority");

                    b.ToTable("comms_ConversationSlaStates", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationSlaTriggerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("EvaluationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstResponseBreachSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FirstResponseWarningSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastEscalatedQueueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LastEscalatedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResolutionBreachSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResolutionWarningSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("WarningThresholdSnapshotMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SlaTriggerState_TenantId");

                    b.HasIndex("TenantId", "ConversationId")
                        .IsUnique()
                        .HasDatabaseName("IX_SlaTriggerState_TenantId_ConversationId");

                    b.HasIndex("TenantId", "FirstResponseBreachSentAtUtc")
                        .HasDatabaseName("IX_SlaTriggerState_TenantId_FirstResponseBreachSentAtUtc");

                    b.HasIndex("TenantId", "ResolutionBreachSentAtUtc")
                        .HasDatabaseName("IX_SlaTriggerState_TenantId_ResolutionBreachSentAtUtc");

                    b.ToTable("comms_ConversationSlaTriggerStates", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventSubType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("RelatedAssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RelatedMessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RelatedSlaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConversationId", "EventType")
                        .HasDatabaseName("IX_Timeline_TenantId_ConversationId_EventType");

                    b.HasIndex("TenantId", "ConversationId", "OccurredAtUtc")
                        .HasDatabaseName("IX_Timeline_TenantId_ConversationId_OccurredAtUtc");

                    b.HasIndex("TenantId", "ConversationId", "Visibility")
                        .HasDatabaseName("IX_Timeline_TenantId_ConversationId_Visibility");

                    b.ToTable("comms_ConversationTimelineEntries", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailDeliveryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("EmailMessageReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("LastStatusAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NotificationsRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageReferenceId");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_EmailDelivery_TenantId_ConversationId");

                    b.HasIndex("TenantId", "EmailMessageReferenceId")
                        .HasDatabaseName("IX_EmailDelivery_TenantId_EmailMessageReferenceId");

                    b.HasIndex("TenantId", "NotificationsRequestId")
                        .HasDatabaseName("IX_EmailDelivery_TenantId_NotificationsRequestId");

                    b.HasIndex("TenantId", "ProviderMessageId")
                        .HasDatabaseName("IX_EmailDelivery_TenantId_ProviderMessageId");

                    b.ToTable("comms_EmailDeliveryStates", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailMessageReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CcAddresses")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CompositionMode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmailDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InReplyToMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InternetMessageId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProviderThreadId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferencesHeader")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("SenderConfigEmail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SenderConfigId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid?>("TemplateConfigId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TemplateKey")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_EmailRefs_TenantId_ConversationId");

                    b.HasIndex("TenantId", "InReplyToMessageId")
                        .HasDatabaseName("IX_EmailRefs_TenantId_InReplyToMessageId");

                    b.HasIndex("TenantId", "InternetMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailRefs_TenantId_InternetMessageId");

                    b.HasIndex("TenantId", "MessageId")
                        .HasDatabaseName("IX_EmailRefs_TenantId_MessageId");

                    b.HasIndex("TenantId", "ProviderMessageId")
                        .HasDatabaseName("IX_EmailRefs_TenantId_ProviderMessageId");

                    b.HasIndex("TenantId", "ProviderThreadId")
                        .HasDatabaseName("IX_EmailRefs_TenantId_ProviderThreadId");

                    b.ToTable("comms_EmailMessageReferences", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailRecipientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("EmailMessageReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsResolvedToParticipant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RecipientSource")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RecipientVisibility")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_EmailRecipients_TenantId_ConversationId");

                    b.HasIndex("TenantId", "EmailMessageReferenceId")
                        .HasDatabaseName("IX_EmailRecipients_TenantId_EmailMessageReferenceId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .HasDatabaseName("IX_EmailRecipients_TenantId_NormalizedEmail");

                    b.HasIndex("TenantId", "EmailMessageReferenceId", "RecipientVisibility")
                        .HasDatabaseName("IX_EmailRecipients_TenantId_EmailMessageReferenceId_Visibility");

                    b.ToTable("comms_EmailRecipientRecords", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailTemplateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BodyHtmlTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTextTemplate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TemplateScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateScope", "TemplateKey")
                        .HasDatabaseName("IX_Templates_TemplateScope_TemplateKey");

                    b.HasIndex("TenantId", "TemplateKey")
                        .HasDatabaseName("IX_Templates_TenantId_TemplateKey");

                    b.ToTable("comms_EmailTemplateConfigs", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ExternalParticipantIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalIdentities_TenantId_NormalizedEmail");

                    b.ToTable("comms_ExternalParticipantIdentities", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("BodyPlainText")
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExternalSenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ExternalSenderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderParticipantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VisibilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_Messages_TenantId_ConversationId");

                    b.HasIndex("TenantId", "ConversationId", "SentAtUtc")
                        .HasDatabaseName("IX_Messages_TenantId_ConversationId_SentAt");

                    b.ToTable("comms_Messages", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_MessageAttachments_TenantId_ConversationId");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("IX_MessageAttachments_TenantId_DocumentId");

                    b.HasIndex("TenantId", "MessageId")
                        .HasDatabaseName("IX_MessageAttachments_TenantId_MessageId");

                    b.ToTable("comms_MessageAttachments", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.MessageMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMentionedUserParticipant")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MentionedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MentionedUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("IX_MessageMentions_TenantId_ConversationId");

                    b.HasIndex("TenantId", "MentionedUserId")
                        .HasDatabaseName("IX_MessageMentions_TenantId_MentionedUserId");

                    b.HasIndex("TenantId", "MessageId")
                        .HasDatabaseName("IX_MessageMentions_TenantId_MessageId");

                    b.HasIndex("TenantId", "MessageId", "MentionedUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageMentions_UniquePerMessageUser");

                    b.ToTable("sc_MessageMentions", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.QueueEscalationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FallbackUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "QueueId")
                        .IsUnique()
                        .HasDatabaseName("IX_QueueEscalationConfig_TenantId_QueueId");

                    b.ToTable("comms_QueueEscalationConfigs", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.TenantEmailSenderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowedForSharedExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReplyToEmail")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FromEmail")
                        .HasDatabaseName("IX_SenderConfigs_TenantId_FromEmail");

                    b.HasIndex("TenantId", "IsDefault")
                        .HasDatabaseName("IX_SenderConfigs_TenantId_IsDefault");

                    b.HasIndex("TenantId", "SenderType")
                        .HasDatabaseName("IX_SenderConfigs_TenantId_SenderType");

                    b.ToTable("comms_TenantEmailSenderConfigs", (string)null);
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("Comms.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comms.Domain.Entities.ConversationReadState", b =>
                {
                    b.HasOne("Comms.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailDeliveryState", b =>
                {
                    b.HasOne("Comms.Domain.Entities.EmailMessageReference", null)
                        .WithMany()
                        .HasForeignKey("EmailMessageReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comms.Domain.Entities.EmailMessageReference", b =>
                {
                    b.HasOne("Comms.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comms.Domain.Entities.Message", b =>
                {
                    b.HasOne("Comms.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comms.Domain.Entities.MessageAttachment", b =>
                {
                    b.HasOne("Comms.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comms.Domain.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
