apiVersion: v1
kind: Service

metadata:
 name: tenant-app
 namespace: dev
 annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

 #labels:
 #app: dotnet-core-service

spec:
  type: LoadBalancer
  selector:
   app: tenant-app

  ports:
  - port: 80
    targetPort: 5005   #change per app