// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reports.Infrastructure.Persistence;

#nullable disable

namespace Reports.Infrastructure.Migrations
{
    [DbContext(typeof(ReportsDbContext))]
    [Migration("20260424000000_AddViewIdToReportSchedule")]
    partial class AddViewIdToReportSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Reports.Domain.Entities.ReportExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("OutputDocumentId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReportDefinitionId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TemplateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.ToTable("rpt_ReportExecutions", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeliveryConfigJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FrequencyConfigJson")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastRunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MinimumTierCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("NextRunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParametersJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequiredFeatureCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("UseOverride")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ViewId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextRunAtUtc");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("IsActive", "NextRunAtUtc");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("rpt_ReportSchedules", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportScheduleRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryResultJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ExportId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("GeneratedFileName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("GeneratedFileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReportScheduleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ReportScheduleId");

                    b.HasIndex("Status");

                    b.HasIndex("ReportScheduleId", "CreatedAtUtc");

                    b.ToTable("rpt_ReportScheduleRuns", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationType");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ProductCode", "OrganizationType");

                    b.ToTable("rpt_ReportDefinitions", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignmentScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MinimumTierCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequiredFeatureCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("ProductCode", "OrganizationType");

                    b.HasIndex("ReportTemplateId", "AssignmentScope", "IsActive");

                    b.ToTable("rpt_ReportTemplateAssignments", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateAssignmentTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ReportTemplateAssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportTemplateAssignmentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ReportTemplateAssignmentId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_rpt_ReportTemplateAssignmentTenants_ReportTemplateAssignmen~1");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("rpt_ReportTemplateAssignmentTenants", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublishedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReportDefinitionId");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("longtext");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ReportTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("rpt_ReportTemplateVersions", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.TenantReportOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BaseTemplateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ColumnConfigJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescriptionOverride")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FilterConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("FormulaConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderConfigJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LayoutConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("MinimumTierCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameOverride")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequiredFeatureCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReportTemplateId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ReportTemplateId", "IsActive");

                    b.ToTable("rpt_TenantReportOverrides", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.TenantReportView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BaseTemplateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ColumnConfigJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FilterConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("FormattingConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("FormulaConfigJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LayoutConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReportTemplateId");

                    b.HasIndex("TenantId", "ReportTemplateId", "IsActive");

                    b.ToTable("rpt_TenantReportViews", (string)null);
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportExecution", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany()
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportSchedule", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany()
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportScheduleRun", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportSchedule", "ReportSchedule")
                        .WithMany("Runs")
                        .HasForeignKey("ReportScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportSchedule");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateAssignment", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany("Assignments")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateAssignmentTenant", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplateAssignment", "Assignment")
                        .WithMany("TenantTargets")
                        .HasForeignKey("ReportTemplateAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateVersion", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.TenantReportOverride", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany()
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.TenantReportView", b =>
                {
                    b.HasOne("Reports.Domain.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany()
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportSchedule", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplate", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Reports.Domain.Entities.ReportTemplateAssignment", b =>
                {
                    b.Navigation("TenantTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
