// <auto-generated />
using CareConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CareConnect.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CareConnectDbContext))]
    [Migration("20260329100004_AddVisibilityScopeToNotes")]
    partial class AddVisibilityScopeToNotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
