// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformAuditEventService.Data;

#nullable disable

namespace PlatformAuditEventService.Data.Migrations
{
    [DbContext(typeof(AuditEventDbContext))]
    [Migration("20260330140138_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlatformAuditEventService.Entities.AuditEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ActorIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<sbyte>("ActorType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ActorUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("mediumtext");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("mediumtext");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("EventCategory")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsReplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("ScopeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("Severity")
                        .HasColumnType("tinyint");

                    b.Property<string>("SourceEnvironment")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SourceService")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserScopeId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("VisibilityScope")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditEventRecords_ActorId");

                    b.HasIndex("AuditId")
                        .IsUnique()
                        .HasDatabaseName("UX_AuditEventRecords_AuditId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditEventRecords_CorrelationId");

                    b.HasIndex("EventCategory")
                        .HasDatabaseName("IX_AuditEventRecords_EventCategory");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_AuditEventRecords_EventType");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_AuditEventRecords_IdempotencyKey");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEventRecords_OccurredAtUtc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_AuditEventRecords_OrganizationId");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("IX_AuditEventRecords_RecordedAtUtc");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_AuditEventRecords_RequestId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_AuditEventRecords_SessionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AuditEventRecords_TenantId");

                    b.HasIndex("VisibilityScope")
                        .HasDatabaseName("IX_AuditEventRecords_VisibilityScope");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditEventRecords_EntityType_EntityId");

                    b.HasIndex("Severity", "RecordedAtUtc")
                        .HasDatabaseName("IX_AuditEventRecords_Severity_RecordedAt");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEventRecords_TenantId_OccurredAt");

                    b.HasIndex("TenantId", "EventCategory", "OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEventRecords_TenantId_Category_OccurredAt");

                    b.ToTable("AuditEventRecords", (string)null);
                });

            modelBuilder.Entity("PlatformAuditEventService.Entities.AuditExportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("ExportId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FilterJson")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("ScopeType")
                        .HasColumnType("tinyint");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AuditExportJobs_CreatedAtUtc");

                    b.HasIndex("ExportId")
                        .IsUnique()
                        .HasDatabaseName("UX_AuditExportJobs_ExportId");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("IX_AuditExportJobs_RequestedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AuditExportJobs_Status");

                    b.HasIndex("ScopeType", "ScopeId")
                        .HasDatabaseName("IX_AuditExportJobs_ScopeType_ScopeId");

                    b.HasIndex("RequestedBy", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditExportJobs_RequestedBy_Status_CreatedAt");

                    b.ToTable("AuditExportJobs", (string)null);
                });

            modelBuilder.Entity("PlatformAuditEventService.Entities.IngestSourceRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceService")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_IngestSourceRegistrations_IsActive");

                    b.HasIndex("SourceSystem", "SourceService")
                        .IsUnique()
                        .HasDatabaseName("UX_IngestSourceRegistrations_SourceSystem_SourceService");

                    b.ToTable("IngestSourceRegistrations", (string)null);
                });

            modelBuilder.Entity("PlatformAuditEventService.Entities.IntegrityCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CheckpointType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("FromRecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ToRecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointType")
                        .HasDatabaseName("IX_IntegrityCheckpoints_CheckpointType");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_IntegrityCheckpoints_CreatedAtUtc");

                    b.HasIndex("CheckpointType", "FromRecordedAtUtc")
                        .HasDatabaseName("IX_IntegrityCheckpoints_CheckpointType_FromAt");

                    b.HasIndex("FromRecordedAtUtc", "ToRecordedAtUtc")
                        .HasDatabaseName("IX_IntegrityCheckpoints_Window");

                    b.ToTable("IntegrityCheckpoints", (string)null);
                });

            modelBuilder.Entity("PlatformAuditEventService.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("SUCCESS");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("INFO");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditEvents_ActorId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditEvents_CorrelationId");

                    b.HasIndex("IngestedAtUtc")
                        .HasDatabaseName("IX_AuditEvents_IngestedAt");

                    b.HasIndex("Source", "EventType")
                        .HasDatabaseName("IX_AuditEvents_Source_EventType");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_AuditEvents_TargetType_TargetId");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEvents_TenantId_OccurredAt");

                    b.HasIndex("Category", "Severity", "Outcome")
                        .HasDatabaseName("IX_AuditEvents_Category_Severity_Outcome");

                    b.ToTable("AuditEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
