// <auto-generated />
using System;
using Flow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowDbContext))]
    [Migration("20260417165304_AddWorkflowSlaE10_3")]
    partial class AddWorkflowSlaE10_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Flow.Domain.Entities.AutomationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ConditionJson")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ConfigJson")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<Guid>("HookId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("RetryDelaySeconds")
                        .HasColumnType("int");

                    b.Property<bool>("StopOnFailure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("HookId", "Order")
                        .IsUnique();

                    b.ToTable("flow_automation_actions", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.AutomationExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ActionOrder")
                        .HasColumnType("int");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("WorkflowAutomationHookId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowAutomationHookId");

                    b.ToTable("flow_automation_execution_logs", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.FlowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("DefaultSlaMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("FLOW_GENERIC");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProductKey");

                    b.ToTable("flow_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Default workflow with standard task lifecycle stages and transitions.",
                            Name = "Standard Task Flow",
                            Status = "Active",
                            TenantId = "default",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("Flow.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("TargetOrgId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TargetRoleKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TargetOrgId");

                    b.HasIndex("TargetRoleKey");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("flow_notifications", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_flow_outbox_status_nextattempt");

                    b.ToTable("flow_outbox_messages", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.ProductWorkflowMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WorkflowInstanceTaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowInstanceTaskId");

                    b.HasIndex("TenantId", "ProductKey");

                    b.HasIndex("TenantId", "ProductKey", "SourceEntityType", "SourceEntityId")
                        .HasDatabaseName("ix_pwm_product_entity");

                    b.ToTable("flow_product_workflow_mappings", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignedToOrgId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("AssignedToRoleKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FlowDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("FLOW_GENERIC");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("WorkflowStageId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToOrgId");

                    b.HasIndex("AssignedToRoleKey");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("FlowDefinitionId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowStageId");

                    b.HasIndex("TenantId", "ProductKey");

                    b.ToTable("flow_task_items", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowAutomationHook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ConfigJson")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("FLOW_GENERIC");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowTransitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowTransitionId");

                    b.HasIndex("TenantId", "ProductKey");

                    b.HasIndex("WorkflowDefinitionId", "WorkflowTransitionId");

                    b.ToTable("flow_automation_hooks", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CurrentStepKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EscalationLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("InitialTaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("LastSlaEvaluatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OverdueSince")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("FLOW_GENERIC");

                    b.Property<string>("SlaStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("OnTrack");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("InitialTaskId");

                    b.HasIndex("SlaStatus")
                        .HasDatabaseName("ix_flow_workflow_instances_slastatus");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_flow_workflow_instances_status_dueat");

                    b.HasIndex("TenantId", "ProductKey");

                    b.ToTable("flow_workflow_instances", (string)null);
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("CanvasX")
                        .HasColumnType("double");

                    b.Property<double?>("CanvasY")
                        .HasColumnType("double");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MappedStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("flow_workflow_stages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsInitial = true,
                            IsTerminal = false,
                            Key = "open",
                            MappedStatus = "Open",
                            Name = "Open",
                            Order = 1,
                            TenantId = "default",
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsInitial = false,
                            IsTerminal = false,
                            Key = "in-progress",
                            MappedStatus = "InProgress",
                            Name = "In Progress",
                            Order = 2,
                            TenantId = "default",
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsInitial = false,
                            IsTerminal = false,
                            Key = "blocked",
                            MappedStatus = "Blocked",
                            Name = "Blocked",
                            Order = 3,
                            TenantId = "default",
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsInitial = false,
                            IsTerminal = true,
                            Key = "done",
                            MappedStatus = "Done",
                            Name = "Done",
                            Order = 4,
                            TenantId = "default",
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            IsInitial = false,
                            IsTerminal = true,
                            Key = "cancelled",
                            MappedStatus = "Cancelled",
                            Name = "Cancelled",
                            Order = 5,
                            TenantId = "default",
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FromStageId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RulesJson")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FromStageId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ToStageId");

                    b.HasIndex("WorkflowDefinitionId", "FromStageId", "ToStageId")
                        .IsUnique();

                    b.ToTable("flow_workflow_transitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Start Work",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Cancel",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000005"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Block",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000003"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Complete",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000004"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Cancel",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000005"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Unblock",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Cancel",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000005"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Reopen",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            FromStageId = new Guid("20000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Reopen",
                            TenantId = "default",
                            ToStageId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WorkflowDefinitionId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Flow.Domain.Entities.AutomationAction", b =>
                {
                    b.HasOne("Flow.Domain.Entities.WorkflowAutomationHook", "Hook")
                        .WithMany("Actions")
                        .HasForeignKey("HookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hook");
                });

            modelBuilder.Entity("Flow.Domain.Entities.AutomationExecutionLog", b =>
                {
                    b.HasOne("Flow.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flow.Domain.Entities.WorkflowAutomationHook", "AutomationHook")
                        .WithMany()
                        .HasForeignKey("WorkflowAutomationHookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationHook");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Flow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Flow.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Task");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Flow.Domain.Entities.ProductWorkflowMapping", b =>
                {
                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flow.Domain.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Flow.Domain.Entities.TaskItem", "WorkflowInstanceTask")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkflowDefinition");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowInstanceTask");
                });

            modelBuilder.Entity("Flow.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("FlowDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Flow.Domain.Entities.WorkflowStage", "WorkflowStage")
                        .WithMany()
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Flow.Domain.Common.ContextReference", "Context", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("ContextId")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("context_id");

                            b1.Property<string>("ContextType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("context_type");

                            b1.Property<string>("Label")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("context_label");

                            b1.HasKey("TaskItemId");

                            b1.HasIndex("ContextType", "ContextId");

                            b1.ToTable("flow_task_items");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("Context");

                    b.Navigation("WorkflowDefinition");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowAutomationHook", b =>
                {
                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany("AutomationHooks")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flow.Domain.Entities.WorkflowTransition", "WorkflowTransition")
                        .WithMany()
                        .HasForeignKey("WorkflowTransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");

                    b.Navigation("WorkflowTransition");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("Flow.Domain.Entities.WorkflowStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Flow.Domain.Entities.TaskItem", "InitialTask")
                        .WithMany()
                        .HasForeignKey("InitialTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentStage");

                    b.Navigation("InitialTask");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowStage", b =>
                {
                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("Flow.Domain.Entities.WorkflowStage", "FromStage")
                        .WithMany("TransitionsFrom")
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flow.Domain.Entities.WorkflowStage", "ToStage")
                        .WithMany("TransitionsTo")
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flow.Domain.Entities.FlowDefinition", "WorkflowDefinition")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("ToStage");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Flow.Domain.Entities.FlowDefinition", b =>
                {
                    b.Navigation("AutomationHooks");

                    b.Navigation("Stages");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowAutomationHook", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Flow.Domain.Entities.WorkflowStage", b =>
                {
                    b.Navigation("TransitionsFrom");

                    b.Navigation("TransitionsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
